# Generated by Django 3.0.5 on 2021-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210305_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
