# Generated by Django 3.0.5 on 2021-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
