# Generated by Django 3.0.5 on 2021-03-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
